# Generated by Django 2.2.6 on 2019-10-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20191029_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'permissions': (('is_usuario', 'Is Usuario'), ('is_admin', 'Is Admin'))},
        ),
    ]
